platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: echo
  args: [hello-Jaswik]

resources:
- name: bharathlabs
  type: git
  source:
    uri: https://github.com/bharathkumar-u/bharathlabs
    branch: master

jobs:
- name: First-Job
  public: true
  plan:
  - get: bharathlabs
  - task: hello-Jaswik
    file: bharathlabs/myconcourse.yml
